config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}, skip: [:registrations]
  root "users#show"
  
  resources :admin_users
  resources :users
  resources :employees
  resources :positions
  resources :departments
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
  belongs_to :position
  has_one_attached :photo

  # Enum para o campo gender
  enum gender: { male: 'Masculino', female: 'Feminino', other: 'Outro' }

  # Enum para o campo status
  enum status: { active: 'Ativo', inactive: 'Inativo', on_leave: 'Em licença' }

  def self.ransackable_attributes(auth_object = nil)
    ["adress", "birth_date", "cep", "city", "complement", "country", "cpf", "created_at", "department_id", "district", "email", "full_name", "gender", "hire_date", "id", "number", "phone", "position_id", "rg", "salary", "status", "updated_at"]
  end

  def formatted_hire_date
    hire_date.strftime("%d/%m/%Y") if hire_date.present?
  end

  def formatted_phone
    cleaned = phone.gsub(/\D/, '')
    
    if cleaned.length == 11
      "(#{cleaned[0..1]})#{cleaned[2..6]}-#{cleaned[7..10]}"
    else
      phone
    end
  end

  def formatted_cpf
    cleaned = cpf.gsub(/\D/, '')

    if cleaned.length == 11
      "#{cleaned[0..2]}.#{cleaned[3..5]}.#{cleaned[6..8]}-#{cleaned[9..10]}"
    else
      cpf
    end
  end

  def full_address
    address_string = "#{adress}, #{number}, #{city}, #{district}, #{country}"

    if complement.present?
      address_string += ", #{complement}"
    end

    address_string
  end

  # Validações
  # validates :full_name, :birth_date, :cpf, :rg, :phone, :email, :position, :adress :hire_date, :salary, :status, presence: true
  # validates :cpf, uniqueness: true
  # validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/concerns/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit, :update, :show, :destroy]

  def index
    @employees = Employee.all
  end

  def show
    
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @employee.update(employee_params)
      redirect_to employees_url(@employee)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @employee.destroy
      redirect_to employees_url
    else
      redirect_to @employee
    end
  end

  private

    def set_employee
      @employee = employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:full_name, :gender, :birth_date, :cpf, :rg, :cep, :country, :city, :adress, :district, :number, :complement, :phone, :email, :salary, :hire_date, :position, :status, :photo, :terms)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!

  def index
    q_params = params[:q].present? ? params[:q].permit! : {}
    @q = Employee.ransack(params[:q])

    if current_user.access_level == 'admin'
      @employees = @q.result(distinct: true)
    else
      @employees = @q.result(distinct: true).where(department_id: current_user.departments.pluck(:id))
    end

    if params[:q].present?
      @employees = @employees.order(hire_date: :asc)
    end
    
    if params[:department_id].present?
      @employees = @employees.where(department_id: params[:department_id])
    end

    if params[:sort_order].present?
      sort_order = params[:sort_order] == 'desc' ? :desc : :asc
      @employees = @employees.order(hire_date: sort_order)
    else
      @employees = @employees.order(hire_date: :asc) if params[:q].blank?
    end
  end

  def show
    
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @employee.update(employee_params)
      redirect_to employees_url(@employee)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @employee.destroy
      redirect_to employees_url
    else
      redirect_to @employee
    end
  end

  private

    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:full_name, :gender, :birth_date, :cpf, :rg, :cep, :country, :city, :adress, :district, :number, :complement, :phone, :email, :salary, :hire_date, :status, :photo, :terms, :position_id, :department_id)
    end
end

app/views/employees/_form.html.erb
<div class="container text-light p-4 rounded">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with model: @employee, local: true, class: 'row g-3 bg-secondary p-4 rounded' do |form| %>

        <div class="col-md-8">
          <%= form.label :full_name, 'Nome Completo', class: 'form-label' %>
          <%= form.text_field :full_name, class: 'form-control bg-dark text-light border-light', id: 'validationDefault01', required: true %>
        </div>

        <div class="col-md-4">
          <%= form.label :gender, 'Gênero', class: 'form-label' %>
          <%= form.select :gender, [['Masculino', 'Masculino'], ['Feminino', 'Feminino'], ['Outro', 'Outro']], { prompt: 'Escolha...' }, { class: 'form-select bg-dark text-light border-light', id: 'validationDefault04', required: true } %>
        </div>

        <div class="col-md-4 ml-3">
          <%= form.label :birth_date, 'Data de Nascimento', class: 'form-label' %>
          <%= form.date_field :birth_date, class: 'form-control dark-input', id: 'validationDefaultDate', required: true %>
        </div>

        <div class="col-md-3">
          <%= form.label :cpf, 'CPF', class: 'form-label' %>
          <%= form.text_field :cpf, class: 'form-control bg-dark text-light border-light', id: 'validationDefault03', required: true %>
        </div>

        <div class="col-md-3">
          <%= form.label :rg, 'RG', class: 'form-label' %>
          <%= form.text_field :rg, class: 'form-control bg-dark text-light border-light', id: 'validationDefault03', required: true %>
        </div>

        <div class="col-12 mb-0">
          <label class="section-label fs-4">Endereço:</label>
        </div>

        <div class="col-md-3 adress-component">
          <%= form.label :cep, 'CEP', class: 'form-label' %>
          <%= form.number_field :cep, class: 'form-control bg-dark text-light border-light', id: 'cep', required: true %>
        </div>

        <div class="col-md-4 adress-component">
          <%= form.label :country, 'Estado', class: 'form-label' %>
          <%= form.select :country, 
              options_for_select([
                ['Acre (AC)', 'AC'], ['Alagoas (AL)', 'AL'], ['Amapá (AP)', 'AP'], ['Amazonas (AM)', 'AM'],
                ['Bahia (BA)', 'BA'], ['Ceará (CE)', 'CE'], ['Distrito Federal (DF)', 'DF'], ['Espírito Santo (ES)', 'ES'],
                ['Goiás (GO)', 'GO'], ['Maranhão (MA)', 'MA'], ['Mato Grosso (MT)', 'MT'], ['Mato Grosso do Sul (MS)', 'MS'],
                ['Minas Gerais (MG)', 'MG'], ['Pará (PA)', 'PA'], ['Paraíba (PB)', 'PB'], ['Paraná (PR)', 'PR'],
                ['Pernambuco (PE)', 'PE'], ['Piauí (PI)', 'PI'], ['Rio de Janeiro (RJ)', 'RJ'], ['Rio Grande do Norte (RN)', 'RN'],
                ['Rio Grande do Sul (RS)', 'RS'], ['Rondônia (RO)', 'RO'], ['Roraima (RR)', 'RR'], ['Santa Catarina (SC)', 'SC'],
                ['São Paulo (SP)', 'SP'], ['Sergipe (SE)', 'SE'], ['Tocantins (TO)', 'TO']
              ], @employee.country), 
              { prompt: @employee.country.present? ? @employee.country : 'Escolha...' },
              { class: 'form-select bg-dark text-light border-light', id: 'uf', required: true } %>
        </div>

        <div class="col-md-5 adress-component">
          <%= form.label :city, 'Cidade', class: 'form-label' %>
          <%= form.text_field :city, class: 'form-control bg-dark text-light border-light', id: 'cidade', required: true %>
        </div>

        <div class="col-md-6 adress-component">
          <%= form.label :adress, 'Rua', class: 'form-label' %>
          <%= form.text_field :adress, class: 'form-control bg-dark text-light border-light', id: 'logradouro', required: true %>
        </div>

        <div class="col-md-4 adress-component">
          <%= form.label :district, 'Bairro', class: 'form-label' %>
          <%= form.text_field :district, class: 'form-control bg-dark text-light border-light', id: 'bairro', required: true %>
        </div>

        <div class="col-md-2 adress-component">
          <%= form.label :number, 'N°', class: 'form-label' %>
          <%= form.number_field :number, class: 'form-control bg-dark text-light border-light', id: 'numero', required: true %>
        </div>

        <div class="col-md-4 adress-component">
          <%= form.label :complement, 'Complemento', class: 'form-label' %>
          <%= form.text_field :complement, class: 'form-control bg-dark text-light border-light', id: 'complemento' %>
        </div>

        <div class="col-12 mb-0">
          <label class="section-label fs-4">Contato:</label>
        </div>

        <div class="col-md-4 mt-2">
          <%= form.label :phone, 'Telefone', class: 'form-label' %>
          <%= form.text_field :phone, class: 'form-control bg-dark text-light border-light', id: 'validationDefault03', required: true %>
        </div>

        <div class="col-md-5 mt-2">
          <%= form.label :email, 'Email', class: 'form-label' %>
          <%= form.text_field :email, class: 'form-control bg-dark text-light border-light', id: 'validationDefault03', required: true %>
        </div>

        <div class="col-12 mb-0">
          <label class="section-label fs-4">Informações Relacionais:</label>
        </div>

        <div class="col-md-3">
          <%= form.label :salary, 'Salário', class: 'form-label' %>
          <%= form.text_field :salary, class: 'form-control bg-dark text-light border-light', id: 'validationDefault03', required: true %>
        </div>

        <div class="col-md-4 ml-3">
          <%= form.label :hire_date, 'Data de Contratação', class: 'form-label' %>
          <%= form.date_field :hire_date, class: 'form-control dark-input', id: 'validationDefaultDate', required: true %>
        </div>

        <div class="col-md-6">
          <%= form.label :department_id, 'Departamento', class: 'form-label' %>
          <%= form.collection_select :department_id, Department.where(status: 'Ativo'), :id, :name, { prompt: 'Escolha...' }, { class: 'form-select bg-dark text-light border-light', id: 'validationDefault04', required: true } %>
        </div>

        <div class="col-md-6">
          <%= form.label :position_id, 'Cargo', class: 'form-label' %>
          <%= form.collection_select :position_id, Position.where(status: 'Ativo'), :id, :name, { prompt: 'Escolha...' }, { class: 'form-select bg-dark text-light border-light', id: 'validationDefault04', required: true } %>
        </div>

        <div class="col-md-4">
          <%= form.label :status, 'Status', class: 'form-label' %>
          <%= form.select :status, 
              [['Ativo', 'active'], ['Inativo', 'inactive'], ['Em licença', 'on_leave']], 
              { prompt: @employee.status.present? ? @employee.status.capitalize : 'Escolha...' },
              { class: 'form-select bg-dark text-light border-light', id: 'validationDefault04', required: true } %>
        </div>

        <div class="col-md-4 mt-4">
            <%= form.label :Foto %>
            <%= form.file_field :photo, class: 'form-control' %>
        </div>              

        <div class="col-12 text-center">
          <%= form.submit 'Enviar', class: 'btn btn-primary' %>
        </div>

      <% end %>
    </div>
  </div>
</div>


<script>
  document.getElementById('cep').addEventListener('blur', function() {
    var cep = this.value.replace(/\D/g, '');

    if (cep.length == 8) {
      var url = `https://viacep.com.br/ws/${cep}/json/`;

      fetch(url)
        .then(response => response.json())
        .then(data => {
          if (!data.erro) {
            document.getElementById('logradouro').value = data.logradouro;
            document.getElementById('bairro').value = data.bairro;
            document.getElementById('cidade').value = data.localidade;
            document.getElementById('uf').value = data.uf;
          } else {
            alert("CEP não encontrado.");
          }
        })
        .catch(error => {
          console.error("Erro ao buscar o CEP: ", error);
          alert("Erro ao buscar o CEP.");
        });
    } else {
      alert("CEP inválido.");
    }
  });
</script>

app/views/employees/edit.html.erb
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="text-center mb-4">
                <h1 class="title">Editar Funcionário</h1>
                <p class="description">Digite os dados a seguir:</p>
            </div>
        </div>
    </div>
</div>

<%= render 'form' %>

app/views/employees/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-center mt-5">
    <div class="col-auto">
      <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group me-5" role="group" aria-label="First group">
            <button id="btnGroupDrop1" type="button" class="btn btn-outline-primary dropdown-toggle me-5" data-bs-toggle="dropdown" aria-expanded="false">
                Data de Contratação
            </button>
        <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
            <li>
                <%= link_to 'Inicial - Final', employees_path(sort_order: 'asc', department_id: params[:department_id], q: params[:q] || {}), class: 'dropdown-item' %>
            </li>
            <li>
                <%= link_to 'Final - Inicial', employees_path(sort_order: 'desc', department_id: params[:department_id], q: params[:q] || {}), class: 'dropdown-item' %>
            </li>
        </ul>
        </div>

        <div class="btn-group me-2 custom-margin-left" role="group" aria-label="Second group">
            <button type="button" class="btn btn-primary">
                <%= link_to "Adicionar Funcionário", new_employee_path, class: "plain-link"%>
            </button>
        </div>

        <div class="btn-group" role="group" aria-label="First group">
            <button id="btnGroupDrop1" type="button" class="btn btn-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                <%= image_tag "filtro.png" %>
            </button>
            <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <li>
                    <%= link_to 'Todos', employees_path(sort_order: params[:sort_order], department_id: nil, q: params[:q]), class: 'dropdown-item' %>
                </li>
                <% current_user.departments.each do |department| %>
                    <li>
                        <%= link_to department.name, employees_path(sort_order: params[:sort_order], department_id: department.id, q: params[:q]), class: 'dropdown-item' %>
                    </li>
                <% end %>
            </ul>
        </div>

      </div>
    </div>
  </div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-7">
            <table class="table mt-2">
                <thead style="text-align: center; vertical-align: middle;">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nome Completo</th>
                        <th scope="col">Cargo</th>
                        <th scope="col">Telefone</th>
                        <th scope="col">Status</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody style="text-align: center; vertical-align: middle;">
                    <% @employees.each do |employee| %>
                    <tr class="-3">
                        <th><%= employee.id %></th>
                        <td><%= employee.full_name %></td>
                        <td><%= Position.find_by(id: employee.position_id).name %></td>
                        <td><%= employee.phone %></td>
                        <% if employee.status == 'active' %>
                            <td><%= image_tag "ativo.png" %></td>
                        <% elsif employee.status == 'inactive' %>
                            <td><%= image_tag "inativo.png" %></td>
                        <% else %>
                            <td><%= image_tag "licenca.png" %></td>
                        <% end %>
                        <td><%= link_to (image_tag "ver.png"), employee_path(employee) %></td>
                        <td><%= link_to (image_tag "editar.png"), edit_employee_path(employee) %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/employees/new.html.erb
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="text-center mb-3">
                <h1 class="title" style="font-size: 2.5rem; font-weight: 700;">Novo Funcionário</h1>
                <p class="description" style="font-size: 1.1rem; margin-bottom: 0rem;">Digite os dados a seguir:</p>
            </div>
        </div>
    </div>
</div>

<%= render 'form' %>

app/views/employees/show.html.erb
<div class="container mt-5">
  <div class="row">
    <!-- Coluna para a foto -->
    <div class="col-md-3">
      <% if @employee.photo.attached? %>
        <%= image_tag @employee.photo, alt: "Foto do Funcionário", class: "img-fluid rounded w-70" %>
      <% else %>
        <%= image_tag "anonimo.png", alt: "Foto Padrão", class: "img-fluid rounded w-70" %>
      <% end %>
    </div>

    <!-- Coluna para o conteúdo -->
    <div class="col-md-9">
      <div class="card">
        <div class="card-body position-relative">


          <div class="position-absolute top-0 end-0 p-2">
            <%= button_to @employee, method: :delete, form: {data: { turbo_confirm: "Você tem certeza?" }}, style: "background: none; border: none; padding: 0; box-shadow: none;" do %>
              <%= image_tag "lixeira.png", alt: "Apagar", style: "width: auto; height: auto;" %>
            <% end %>
          </div>

          <h4 class="card-title">Nome Completo: <strong><%= @employee.full_name %></strong></h4>
          
          <p class="card-text"><strong>Cargo:</strong> <%= Position.find_by(id: @employee.position_id).name %></p>
          <p class="card-text"><strong>Data de Contratação:</strong> <%= @employee.formatted_hire_date %></p>
          <p class="card-text"><strong>Telefone:</strong> <%= @employee.formatted_phone %></p>
          <p class="card-text"><strong>E-mail:</strong> <%= @employee.email %></p>
          <p class="card-text"><strong>Status:</strong> 
          
          <% if @employee.status == 'active' %>
            <%= "Ativo" %>
          <% elsif @employee.status == 'inactive' %>
            <%= "Inativo" %>
          <% else %>
            <%= "Em Licença" %>
          <% end %>

          </p>

          <p class="card-text"><strong>Salário:</strong> <%= number_to_currency(@employee.salary, unit: "R$", separator: ",", delimiter: ".", precision: 2) %></p>

          <!-- Botão para exibir dados sensíveis -->
          <button class="btn btn-warning mt-3" onclick="toggleSensitiveData()">Exibir Dados Sensíveis</button>

          <%= link_to 'Voltar', employees_path, class: 'btn btn-warning mt-3' %>

          <!-- Dados sensíveis ocultos -->
          <div id="sensitive-data" style="display: none;" class="mt-3">
            <p class="card-text"><strong>CPF:</strong> <%= @employee.formatted_cpf %></p>
            <p class="card-text"><strong>RG:</strong> <%= @employee.rg %></p>
            <p class="card-text"><strong>Endereço:</strong> <%= @employee.full_address %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function toggleSensitiveData() {
    var sensitiveData = document.getElementById('sensitive-data');
    if (sensitiveData.style.display === 'none') {
      sensitiveData.style.display = 'block';
    } else {
      sensitiveData.style.display = 'none';
    }
  }
</script>