config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}, skip: [:registrations]
  root "users#show"
  
  resources :admin_users
  resources :users
  resources :employees
  resources :positions
  resources :departments
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :department
  has_many :employees

  validates :name, :description, :department_id, :level, :base_salary, :status, presence: true
  validates :base_salary, numericality: { greater_than_or_equal_to: 0 }

  enum level: { junior: 'Júnior', pleno: 'Pleno', senior: 'Sênior', not_applicable: 'Não se aplica' }
  
  enum status: { active: 'Ativo', inactive: 'Inativo' }
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [ :show, :update, :edit, :destroy]
  before_action :authenticate_user!

  def index
    q_params = params[:q].present? ? params[:q].permit! : {}
    @q = Position.ransack(q_params)
  
    # Inicializa @positions com a busca do Ransack
    if current_user.access_level == 'admin'
      @positions = @q.result(distinct: true)
    else
      @positions = @q.result(distinct: true).where(department_id: current_user.departments.pluck(:id))
    end
  
    # Aplica o filtro de departamento, se presente
    if params[:department_id].present?
      @positions = @positions.where(department_id: params[:department_id])
    end
  
    # Aplica o filtro de salário
    min_salary = params[:min_salary].present? ? params[:min_salary].to_f : nil
    max_salary = params[:max_salary].present? ? params[:max_salary].to_f : nil
  
    if min_salary || max_salary
      if min_salary && max_salary
        @positions = @positions.where(base_salary: min_salary..max_salary)
      elsif min_salary
        @positions = @positions.where("base_salary >= ?", min_salary)
      elsif max_salary
        @positions = @positions.where("base_salary <= ?", max_salary)
      end
    end
  
    # Ordenação
    @positions = @positions.order(base_salary: params[:sort_order]) if params[:sort_order].present?
  end

  def show
  end

  def new
    @position = Position.new
  end

  def create
    @position = Position.new(position_params)
    
    if @position.save
      redirect_to positions_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @position.update(position_params)
      redirect_to positions_url(@position), notice: 'Cargo atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    if @position.destroy
      redirect_to positions_url, notice: 'Cargo apagado com sucesso.'
    else
      redirect_to @position
    end
  end

  private

  def set_position
    @position = Position.find(params[:id])
  end

  def position_params
    params.require(:position).permit(:name, :description, :level, :base_salary, :requirements, :benefits, :status, :department_id)
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<div class="container text-light p-4 rounded">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with model: @position, local: true, class: 'row g-3 bg-secondary p-4 rounded' do |form| %>

        <div class="col-md-5">
          <%= form.label :name, 'Nome do Cargo', class: 'form-label' %>
          <%= form.text_field :name, class: 'form-control bg-dark text-light border-light', id: 'validationDefault01', required: true %>
        </div>

        <div class="col-md-6">
          <%= form.label :department_id, 'Departamento', class: 'form-label' %>
          <%= form.collection_select :department_id, Department.where(status: 'Ativo'), :id, :name, { prompt: 'Escolha...' }, { class: 'form-select bg-dark text-light border-light', id: 'validationDefault04', required: true } %>
        </div>

        <div class="col-md-6">
          <%= form.label :description, 'Descrição do Cargo', class: 'form-label' %>
          <%= form.text_area :description, class: 'form-control bg-dark text-light border-light', rows: 3, id: 'validationDefault02', required: true %>
        </div>

        <div class="col-md-5">
          <%= form.label :base_salary, 'Salário Base', class: 'form-label' %>
          <%= form.number_field :base_salary, class: 'form-control bg-dark text-light border-light', id: 'validationDefault03', required: true, step: '0.01', min: '0' %>
        </div>

        <div class="col-md-6">
          <%= form.label :level, 'Nível do Cargo', class: 'form-label' %>
          <%= form.select :level, [['Júnior', 'Júnior'], ['Pleno', 'Pleno'], ['Sênior', 'Sênior'], ['Não se aplica', 'Não se aplica']], { prompt: 'Escolha...' }, { class: 'form-select bg-dark text-light border-light', id: 'validationDefault04', required: true } %>
        </div>

        <div class="col-md-4">
          <%= form.label :status, 'Status', class: 'form-label' %>
          <%= form.select :status, 
              [['Ativo', 'active'], ['Inativo', 'inactive']], 
              { prompt: @position.status.present? ? @position.status.capitalize : 'Escolha...' },
              { class: 'form-select bg-dark text-light border-light', id: 'validationDefault04', required: true } %>
        </div>

        <div class="col-md-6">
          <%= form.label :requirements, 'Requerimentos', class: 'form-label' %>
          <%= form.text_area :requirements, class: 'form-control bg-dark text-light border-light', rows: 3, id: 'validationDefault02', required: true %>
        </div>   

        <div class="col-md-6">
          <%= form.label :benefits, 'Benefícios', class: 'form-label' %>
          <%= form.text_area :benefits, class: 'form-control bg-dark text-light border-light', rows: 3, id: 'validationDefault02', required: true %>
        </div>            

        <div class="col-12 text-center">
          <%= form.submit 'Enviar', class: 'btn btn-primary' %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/positions/edit.html.erb
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="text-center mb-3">
                <h1 class="title" style="font-size: 2.5rem; font-weight: 700;">Editar Cargo</h1>
                <p class="description" style="font-size: 1.1rem; margin-bottom: 0rem;">Digite os dados a seguir:</p>
                <p class="description" style="font-size: 1rem; color: #6c757d;">(Nos campos de texto livre, dividir por ';' ou quebra de linha)</p>
            </div>
        </div>
    </div>
</div>


<%= render 'form' %>

app/views/positions/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-center mt-5">
    <div class="col-auto">
      <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group me-5" role="group" aria-label="Dropdown com intervalo de salário">
          <button id="btnGroupDropSalary" type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Salário Base
          </button>
          <ul class="dropdown-menu" aria-labelledby="btnGroupDropSalary">
            <li>
              <div class="dropdown-item">
                <form action="<%= positions_path %>" method="get">
                  <div class="mb-3">
                    <label for="minSalary" class="form-label">Salário Mínimo</label>
                    <input type="number" class="form-control" id="minSalary" name="min_salary" placeholder="Ex: 3000" min="0" value="<%= params[:min_salary] %>">
                  </div>
                  <div class="mb-3">
                    <label for="maxSalary" class="form-label">Salário Máximo</label>
                    <input type="number" class="form-control" id="maxSalary" name="max_salary" placeholder="Ex: 100000" min="0" value="<%= params[:max_salary] %>">
                  </div>
                  <input type="hidden" name="department_id" value="<%= params[:department_id] %>">
                  <input type="hidden" name="sort_order" value="<%= params[:sort_order] %>">
                  <button type="button" class="btn btn-danger" onclick="window.location.href='/positions';">
                    Apagar
                  </button>
                  <button type="submit" class="btn btn-primary">Aplicar</button>
                </form>
              </div>
            </li>
          </ul>
        </div>

        <div class="btn-group me-2" role="group" aria-label="Second group">
          <button type="button" class="btn btn-primary custom-margin-left">
            <%= link_to "Adicionar Cargo", new_position_path, class: "plain-link"%>
          </button>
        </div>
        <div class="btn-group" role="group" aria-label="Dropdown de Departamentos">
          <button id="btnGroupDropDepartment" type="button" class="btn btn-secondary" data-bs-toggle="dropdown" aria-expanded="false">
            <%= image_tag "filtro.png", alt: "Filtro", class: "img-fluid" %>
          </button>
          <ul class="dropdown-menu" aria-labelledby="btnGroupDropDepartment">
            <li>
              <%= link_to 'Todos', positions_path(min_salary: params[:min_salary], max_salary: params[:max_salary]), class: 'dropdown-item' %>
            </li>
            <% current_user.departments.each do |department| %>
              <li>
                <%= link_to department.name, positions_path(department_id: department.id, min_salary: params[:min_salary], max_salary: params[:max_salary], sort_order: params[:sort_order]), class: 'dropdown-item' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .dropdown-toggle:focus {
    outline: none;
    box-shadow: none;
  }

  .dropdown-menu {
    padding: 15px;
    transition: none; 
  }

  .dropdown-item {
    pointer-events: auto; 
  }

  .dropdown-item:hover, .dropdown-item:focus {
    background-color: #f8f9fa; 
  }
</style>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-7">
      <table class="table mt-2">
        <thead style="text-align: center; vertical-align: middle;">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Departamento</th>
            <th scope="col">Salário Base</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody style="text-align: center; vertical-align: middle;">
          <% @positions.each do |position| %>
            <tr class="-3">
              <th><%= position.id %></th>
              <td><%= position.name %></td>
              <td><%= position.department.name %></td>
              <td><%= number_to_currency(position.base_salary, unit: "R$", separator: ",", delimiter: ".", precision: 2) %></td>
              <% if position.status == 'active' %>
                <td><%= image_tag "ativo.png" %></td>
              <% elsif position.status == 'inactive' %>
                <td><%= image_tag "inativo.png" %></td>
              <% end %>

              <td><%= link_to (image_tag "ver.png"), position_path(position) %></td>
            
              <% if Department.find_by(id: position.department_id).status == 'active'%>
                <td>
                  <%= link_to (image_tag "editar.png"), edit_position_path(position) %>
                </td>
              <% else %>
                <td>
                  <%= image_tag "editar.png", style: "opacity: 0.5;" %>
                </td>
              <% end %>
              
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/positions/new.html.erb
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="text-center mb-3">
                <h1 class="title" style="font-size: 2.5rem; font-weight: 700;">Novo Cargo</h1>
                <p class="description" style="font-size: 1.1rem; margin-bottom: 0rem;">Digite os dados a seguir:</p>
                <p class="description" style="font-size: 1rem; color: #6c757d;">(Nos campos de texto livre, dividir por ';' ou quebra de linha)</p>
            </div>
        </div>
    </div>
</div>


<%= render 'form' %>

app/views/positions/show.html.erb
<div class="container mt-5">
  <div class="row">
    <!-- Coluna para o conteúdo -->
    <div class="col-md-12">
      <div class="card">
        <div class="card-body position-relative">

          <div class="position-absolute top-0 end-0 p-2">
            <%= button_to @position, method: :delete, form: {data: { turbo_confirm: "Você tem certeza?" }}, style: "background: none; border: none; padding: 0; box-shadow: none;" do %>
              <%= image_tag "lixeira.png", alt: "Apagar", style: "width: auto; height: auto;" %>
            <% end %>
          </div>

          <h4 class="card-title">Nome: <strong><%= @position.name %></strong></h4>

          <p class="card-text"><strong>Descrição:</strong> <%= @position.description %></p>
          <p class="card-text"><strong>Departamento:</strong> <%= Department.find_by(id: @position.department_id).name %></p>
          <p class="card-text"><strong>Nível:</strong> 
            <% if @position.level == 'junior' %>
              <%= "Júnior" %>
            <% elsif @position.level == 'pleno' %>
              <%= "Pleno" %>
            <% elsif @position.level == 'senior' %>
              <%= "Sênior" %>
            <% else %>
              <%= "Não se aplica" %>
            <% end %>
          </p>

          <p class="card-text"><strong>Status:</strong>
            <% if @position.status == 'active' %>
              <%= "Ativo" %>
            <% elsif @position.status == 'inactive' %>
              <%= "Inativo" %>
            <% else %>
              <%= "Em Licença" %>
            <% end %>
          </p>

          <p class="card-text"><strong>Salário Base:</strong> <%= number_to_currency(@position.base_salary, unit: "R$", separator: ",", delimiter: ".", precision: 2) %></p>

        <div class="row">
            <div class="col-md-3">
                <p class="card-text mb-1"><strong>Requisitos:</strong></p>
                <ul class="mt-0">
                <% @position.requirements.split(/;|\n/).each do |requirement| %>
                    <li><%= requirement.strip %></li>
                <% end %>
                </ul>
            </div>

            <div class="col-md-6">
                <p class="card-text mb-1"><strong>Benefícios:</strong></p>
                <ul class="mt-0">
                <% @position.benefits.split(/;|\n/).each do |benefit| %>
                    <li><%= benefit.strip %></li>
                <% end %>
                </ul>
            </div>
        </div>


        <%= link_to 'Voltar', positions_path, class: 'btn btn-warning mt-3' %>

        </div>
      </div>
    </div>
  </div>
</div>