config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}, skip: [:registrations]
  root "users#show"
  
  resources :admin_users
  resources :users
  resources :employees
  resources :positions
  resources :departments
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :departments_users
  has_many :users, through: :departments_users
  has_many :employees
  has_many :positions

  before_update :check_deactivation, if: :status_changed?

  def full_address
    address_string = "#{street}, #{number}, #{city}, #{district}, #{state}"

    if complement.present?
      address_string += ", #{complement}"
    end

    address_string
  end

  enum status: { active: 'Ativo', inactive: 'Inativo' }

  private

  def check_deactivation
    if status == 'inactive'
      positions.update_all(status: 'inactive')

      employees.update_all(status: 'on_leave')
    end
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /departments or /departments.json
  def index
    @departments = current_user.departments
  end

  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to departments_url, notice: "Departmento foi criado" }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to departments_url, notice: "Departmento foi atualizado" }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @department.destroy!

    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Departmento foi deletado" }
      format.json { head :no_content }
    end
  end

  private
    def set_department
      @department = Department.find(params[:id])
    end

    def department_params
      params.require(:department).permit(:name, :description, :code, :street, :number, :complement, :district, :city, :state, :cep, :status)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<div class="container text-light p-4 rounded">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= form_with model: @department, local: true, class: 'row g-3 bg-secondary p-4 rounded' do |form| %>

        <div class="col-md-12">
          <%= form.label :name, 'Nome', class: 'form-label' %>
          <%= form.text_field :name, class: 'form-control bg-dark text-light border-light', id: 'validationDefaultName', required: true %>
        </div>

        <div class="col-md-12">
          <%= form.label :description, 'Descrição', class: 'form-label' %>
          <%= form.text_area :description, class: 'form-control bg-dark text-light border-light', id: 'validationDefaultDescription', rows: 3, required: true %>
        </div>

        <div class="col-md-12">
          <%= form.label :code, 'Código', class: 'form-label' %>
          <%= form.text_field :code, class: 'form-control bg-dark text-light border-light', id: 'validationDefaultCode', required: true %>
        </div>

        <div class="col-md-3">
          <%= form.label :cep, 'CEP', class: 'form-label' %>
          <%= form.number_field :cep, class: 'form-control bg-dark text-light border-light', id: 'cep', required: true %>
        </div>

        <div class="col-md-4">
          <%= form.label :street, 'Rua', class: 'form-label' %>
          <%= form.text_field :street, class: 'form-control bg-dark text-light border-light', id: 'logradouro', required: true %>
        </div>

        <div class="col-md-2">
          <%= form.label :number, 'Número', class: 'form-label' %>
          <%= form.number_field :number, class: 'form-control bg-dark text-light border-light', id: 'numero', required: true %>
        </div>

        <div class="col-md-3">
          <%= form.label :complement, 'Complemento', class: 'form-label' %>
          <%= form.text_field :complement, class: 'form-control bg-dark text-light border-light', id: 'complemento' %>
        </div>

        <div class="col-md-4">
          <%= form.label :district, 'Bairro', class: 'form-label' %>
          <%= form.text_field :district, class: 'form-control bg-dark text-light border-light', id: 'bairro', required: true %>
        </div>

        <div class="col-md-4">
          <%= form.label :city, 'Cidade', class: 'form-label' %>
          <%= form.text_field :city, class: 'form-control bg-dark text-light border-light', id: 'cidade', required: true %>
        </div>

        <div class="col-md-4">
          <%= form.label :state, 'Estado', class: 'form-label' %>
          <%= form.select :state, 
              options_for_select([
                ['Acre (AC)', 'AC'], ['Alagoas (AL)', 'AL'], ['Amapá (AP)', 'AP'], ['Amazonas (AM)', 'AM'],
                ['Bahia (BA)', 'BA'], ['Ceará (CE)', 'CE'], ['Distrito Federal (DF)', 'DF'], ['Espírito Santo (ES)', 'ES'],
                ['Goiás (GO)', 'GO'], ['Maranhão (MA)', 'MA'], ['Mato Grosso (MT)', 'MT'], ['Mato Grosso do Sul (MS)', 'MS'],
                ['Minas Gerais (MG)', 'MG'], ['Pará (PA)', 'PA'], ['Paraíba (PB)', 'PB'], ['Paraná (PR)', 'PR'],
                ['Pernambuco (PE)', 'PE'], ['Piauí (PI)', 'PI'], ['Rio de Janeiro (RJ)', 'RJ'], ['Rio Grande do Norte (RN)', 'RN'],
                ['Rio Grande do Sul (RS)', 'RS'], ['Rondônia (RO)', 'RO'], ['Roraima (RR)', 'RR'], ['Santa Catarina (SC)', 'SC'],
                ['São Paulo (SP)', 'SP'], ['Sergipe (SE)', 'SE'], ['Tocantins (TO)', 'TO']
              ], @department.state), 
              { prompt: @department.state.present? ? @department.state : 'Escolha...' },
              { class: 'form-select bg-dark text-light border-light', id: 'uf', required: true } %>
        </div>

        <div class="col-md-4">
          <%= form.label :status, 'Status', class: 'form-label' %>
          <%= form.select :status, 
              [['Ativo', 'active'], ['Inativo', 'inactive']], 
              { prompt: @department.status.present? ? @department.status.capitalize : 'Escolha...' },
              { class: 'form-select bg-dark text-light border-light', id: 'validationDefaultStatus', required: true } %>
        </div>

        <div class="col-12 text-center mt-3">
          <%= form.submit 'Salvar', class: 'btn btn-primary' %>
        </div>

      <% end %>
    </div>
  </div>
</div>

<script>
  document.getElementById('cep').addEventListener('blur', function() {
    var cep = this.value.replace(/\D/g, '');

    if (cep.length == 8) {
      var url = `https://viacep.com.br/ws/${cep}/json/`;

      fetch(url)
        .then(response => response.json())
        .then(data => {
          if (!data.erro) {
            document.getElementById('logradouro').value = data.logradouro;
            document.getElementById('bairro').value = data.bairro;
            document.getElementById('cidade').value = data.localidade;
            document.getElementById('uf').value = data.uf;
          } else {
            alert("CEP não encontrado.");
          }
        })
        .catch(error => {
          console.error("Erro ao buscar o CEP: ", error);
          alert("Erro ao buscar o CEP.");
        });
    } else {
      alert("CEP inválido.");
    }
  });
</script>

app/views/departments/edit.html.erb
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="text-center mb-3">
                <h1 class="title" style="font-size: 2.5rem; font-weight: 700;">Editar Departamento</h1>
                <p class="description" style="font-size: 1.1rem; margin-bottom: 0rem;">Digite os dados a seguir:</p>
            </div>
        </div>
    </div>
</div>


<%= render 'form' %>

app/views/departments/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-center mt-5">
    <div class="col-auto">
      <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group me-5 md-5" role="group" aria-label="Dropdown com intervalo de salário">
          
        </div>
        <div class="btn-group me-2" role="group" aria-label="Second group">
          <button type="button" class="btn btn-primary custom-margin-left">
            <%= link_to "Adicionar Departamento", new_department_path, class: "plain-link"%>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .dropdown-toggle:focus {
    outline: none;
    box-shadow: none;
  }

  .dropdown-menu {
    padding: 15px;
    transition: none;
  }

  .dropdown-item {
    pointer-events: auto;
  }

  .dropdown-item:hover, .dropdown-item:focus {
    background-color: #f8f9fa;
  }
</style>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-7">
      <table class="table mt-2">
        <thead style="text-align: center; vertical-align: middle;">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Código</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        
        <tbody style="text-align: center; vertical-align: middle;">
          <% @departments.each do |department| %>
            <tr class="-3">
              <th><%= department.id %></th>
              <td><%= department.name %></td>
              <td><%= department.code %></td>
              <% if department.status == 'active' %>
                <td><%= image_tag "ativo.png" %></td>
              <% elsif department.status == 'inactive' %>
                <td><%= image_tag "inativo.png" %></td>
              <% end %>
              <td><%= link_to (image_tag "ver.png"), department_path(department) %></td>
              <td><%= link_to (image_tag "editar.png"), edit_department_path(department) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/departments/new.html.erb
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="text-center mb-3">
                <h1 class="title" style="font-size: 2.5rem; font-weight: 700;">Novo Departamento</h1>
                <p class="description" style="font-size: 1.1rem; margin-bottom: 0rem;">Digite os dados a seguir:</p>
            </div>
        </div>
    </div>
</div>


<%= render 'form' %>

app/views/departments/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <!-- Coluna para o conteúdo -->
    <div class="col-md-8"> <!-- Ajuste o número aqui para definir a largura -->
      <div class="card">
        <div class="card-body department-relative">

          <div class="position-absolute top-0 end-0 p-2">
            <%= button_to @department, method: :delete, form: {data: { turbo_confirm: "Você tem certeza?" }}, style: "background: none; border: none; padding: 0; box-shadow: none;" do %>
              <%= image_tag "lixeira.png", alt: "Apagar", style: "width: auto; height: auto;" %>
            <% end %>
          </div>

          <h4 class="card-title">Nome: <strong><%= @department.name %></strong></h4>

          <p class="card-text"><strong>Descrição:</strong> <%= @department.description %></p>
          <p class="card-text"><strong>Código:</strong> <%= @department.code %></p>

          <p class="card-text"><strong>Status:</strong>
            <% if @department.status == 'active' %>
              <%= "Ativo" %>
            <% elsif @department.status == 'inactive' %>
              <%= "Inativo" %>
            <% end %>
          </p>

          <p class="card-text"><strong>Endereço:</strong> <%= @department.full_address %></p>

          <%= link_to 'Voltar', departments_path, class: 'btn btn-warning mt-3' %>

        </div>
      </div>
    </div>
  </div>
</div>