config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}, skip: [:registrations]
  root "users#show"
  
  resources :admin_users
  resources :users
  resources :employees
  resources :positions
  resources :departments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :departments_users
  has_many :departments, through: :departments_users
  before_validation :ensure_admin_for_first_user, on: :create
  after_create :assign_departments
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true
  validates :access_level, inclusion: { in: %w(admin hr_manager) }
  
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, if: :password_required?

  private

  def ensure_admin_for_first_user
    if User.count.zero?
      self.access_level = 'admin'
    end
  end

  def assign_departments
    if access_level == 'admin'
      departments = Department.all
      self.departments = departments
      Rails.logger.info "Assigned departments: #{departments.pluck(:name).join(', ')} to user #{self.name}"
    end
  end

  def password_required?
    password.present? || password_confirmation.present?
  end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.must_change_password = true unless no_users?
    if @user.save
      redirect_to admin_users_path, notice: 'Usuário criado com sucesso.'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      @user.update(must_change_password: false) if params[:user][:password].present?
      redirect_to admin_users_path, notice: 'Usuário atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: 'Usuário excluído com sucesso.'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :access_level, department_ids: [])
  end

  def no_users?
    User.count.zero?
  end

  def check_admin
    unless current_user.access_level == 'admin'
      redirect_to root_path, alert: 'Você não tem permissão para acessar esta página.'
    end
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sign Up</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
      body {
        background-color: #121212; /* Dark background for the entire page */
        color: #e0e0e0; /* Light text color */
        margin: 0;
        padding: 0;
        overflow-x: hidden; /* Prevent horizontal scrolling */
      }
      .signup-container {
        max-width: 420px;
        margin: auto;
        padding: 20px;
        border: 1px solid #333; /* Dark border */
        border-radius: 8px;
        background-color: #1e1e1e; /* Dark form background */
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5); /* Darker shadow */
      }
      .signup-header {
        text-align: center;
        margin-bottom: 20px;
      }
      .form-control, .form-check-input {
        background-color: #333; /* Dark input background */
        color: #e0e0e0; /* Light input text color */
        border: 1px solid #444; /* Darker border */
      }
      .form-control::placeholder {
        color: #888; /* Placeholder color */
      }
      .btn-primary {
        background-color: #007bff; /* Primary button color */
        border: none;
      }
      .btn-primary:hover {
        background-color: #0056b3; /* Darker shade on hover */
      }
      .btn-success {
        background-color: #28a745; /* Success button color */
        border: none;
      }
      .btn-success:hover {
        background-color: #218838; /* Darker shade on hover */
      }
      .text-body-secondary {
        color: #888; /* Secondary text color */
      }
      .text-body-secondary a {
        color: #007bff; /* Link color */
      }
      .text-body-secondary a:hover {
        text-decoration: underline;
      }
      .form-text {
        color: #fff; /* White color for the form text */
      }
      .department-message {
        color: #28a745; /* Success message color */
        font-weight: bold;
      }
    </style>
  </head>
  <body>
    <main class="signup-container mt-5">
      <div class="signup-header">
        <h2>Editar</h2>
      </div>

      <%= form_with model: @user, url: admin_user_path(@user), local: true do |f|  %>
        <% if @user.errors.any? %>
            <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> proibiram este usuário de ser salvo:</h2>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
            </div>
        <% end %>

        <div class="form-floating mb-3">
          <%= f.text_field :name, class: 'form-control', id: 'floatingFullName', placeholder: 'Full Name', autofocus: true, autocomplete: "name" %>
          <label for="floatingFullName">Nome</label>
        </div>

        <div class="form-floating mb-3">
          <%= f.email_field :email, class: 'form-control', id: 'floatingEmail', placeholder: 'name@example.com', autocomplete: "email" %>
          <label for="floatingEmail">Email</label>
        </div>

        <div class="form-floating mb-3">
          <%= f.password_field :password, class: 'form-control', id: 'floatingPassword', placeholder: 'Password', autocomplete: "new-password" %>
          <label for="floatingPassword">Senha</label>
          <% if @minimum_password_length %>
            <small class="form-text">(mínimo de <%= @minimum_password_length %> caracteres)</small>
          <% end %>
        </div>

        <div class="form-floating mb-3">
          <%= f.password_field :password_confirmation, class: 'form-control', id: 'floatingPasswordConfirmation', placeholder: 'Confirm Password', autocomplete: "new-password" %>
          <label for="floatingPasswordConfirmation">Confirmar Senha</label>
        </div>

        <div class="mb-3">
          <% if User.count.zero? %>
            <%= f.hidden_field :access_level, value: 'admin' %>
            <p class="text-warning">O primeiro usuário será cadastrado como Administrador.</p>
          <% else %>
            <% if @user.access_level != 'admin' %>
                <div class="mb-3">
                <%= f.label :Nível_de_Acesso, class: 'form-label' %>
                <%= f.select :access_level, options_for_select([['Administrador', 'admin'], ['Gestor de RH', 'hr_manager']], f.object.access_level), { include_blank: 'Selecione...' }, { class: 'form-select' } %>
                </div>
            <% end %>
          <% end %>
        </div>

        <div class="mb-3" id="departmentsField">
          <%= f.label :department_ids, 'Departamentos', class: 'form-label' %>
          <%= f.collection_check_boxes :department_ids, Department.all, :id, :name do |b| %>
            <div class="form-check">
              <%= b.check_box(class: 'form-check-input') %>
              <%= b.label(class: 'form-check-label') %>
            </div>
          <% end %>
        </div>

        <div id="adminMessage" class="department-message" style="display: none;">
          Você tem acesso a todos os departamentos.
        </div>

        <button class="btn btn-success w-100 py-2" type="submit">Editar</button>
      <% end %>
    </main>

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

<script>
    document.addEventListener('DOMContentLoaded', function() {
    var accessLevelField = document.querySelector('select[name="user[access_level]"]');
    var departmentsField = document.getElementById('departmentsField');
    var adminMessage = document.getElementById('adminMessage');
    
    // Exibir os departamentos por padrão
    departmentsField.style.display = 'none';
    adminMessage.style.display = 'none';

    accessLevelField.addEventListener('change', function() {
      console.log("Access Level Changed: ", accessLevelField.value); // Debug log
      if (accessLevelField.value === 'hr_manager') {
        departmentsField.style.display = 'block';
        adminMessage.style.display = 'none';
      } else if (accessLevelField.value === 'admin') {
        departmentsField.style.display = 'none';
        adminMessage.style.display = 'block';
      } else {
        departmentsField.style.display = 'none';
        adminMessage.style.display = 'none';
      }
    });
  });
</script>

app/views/admin_users/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-center mt-5">
    <div class="col-auto">
      <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group me-5 md-5" role="group" aria-label="Dropdown com intervalo de salário">
          
        </div>
        <div class="btn-group me-2" role="group" aria-label="Second group">
          <button type="button" class="btn btn-primary custom-margin-left">
            <%= link_to "Adicionar Usuário", new_user_path, class: "plain-link"%>
          </button>
        </div>

      </div>
    </div>
  </div>
</div>

<style>
  .dropdown-toggle:focus {
    outline: none;
    box-shadow: none;
  }

  .dropdown-menu {
    padding: 15px;
    transition: none;
  }

  .dropdown-item {
    pointer-events: auto;
  }

  .dropdown-item:hover, .dropdown-item:focus {
    background-color: #f8f9fa;
  }
</style>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-7">
      <table class="table mt-2">
        <thead style="text-align: center; vertical-align: middle;">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Email</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        
        <tbody style="text-align: center; vertical-align: middle;">
          <% @users.each do |user| %>
            <tr class="-3">
              <td><%= user.id %></td>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= link_to (image_tag "ver.png"), admin_user_path(user) %></td>
              <td><%= link_to (image_tag "editar.png"), edit_admin_user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin_users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Detalhes do Usuário</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container mt-4">
    <h1 class="text-center">Detalhes do Usuário</h1>

    <div class="card custom-card">
      <div class="card-body">

        <% if @user.access_level != 'admin' %>
            <div class="position-absolute top-0 end-0 p-2">
                <%= button_to @department, method: :delete, form: {data: { turbo_confirm: "Você tem certeza?" }}, style: "background: none; border: none; padding: 0; box-shadow: none;" do %>
                <%= image_tag "lixeira.png", alt: "Apagar", style: "width: auto; height: auto;" %>
                <% end %>
            </div>
        <% end %>

        <h5 class="card-title"><%= @user.name %></h5>
        <p class="card-text"><strong>Email:</strong> <%= @user.email %></p>
        <p class="card-text"><strong>Nível de Acesso:</strong> <%= @user.access_level %></p>

        <h6>Departamentos:</h6>
        <ul>
          <% @user.departments.each do |department| %>
            <li><%= department.name %></li>
          <% end %>
        </ul>

        <div class="mt-3 d-flex justify-content-center">
          <%= link_to 'Editar Perfil', edit_admin_user_path(@user), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>